// Findings logic, ported from app/postprocess.py (kept in step by test/findings.test.mjs,
// which replays cases generated by the Python code).

export const FINDING_TYPES = [
  "tooth",
  "caries",
  "periapical_lesion",
  "restoration",
  "crown",
  "root_canal_treatment",
  "implant",
  "impacted_tooth",
  "bone_loss",
  "calculus",
];

export const PATHOLOGY = new Set(["caries", "periapical_lesion", "impacted_tooth", "bone_loss", "calculus"]);

export const LABELS = {
  tooth: "Tooth",
  caries: "Caries",
  periapical_lesion: "Periapical radiolucency",
  restoration: "Restoration",
  crown: "Crown",
  root_canal_treatment: "Root canal treatment",
  implant: "Implant",
  impacted_tooth: "Impacted tooth",
  bone_loss: "Alveolar bone loss",
  calculus: "Calculus",
};

export const area = (b) => Math.max(0, b.x2 - b.x1) * Math.max(0, b.y2 - b.y1);
export const center = (b) => [(b.x1 + b.x2) / 2, (b.y1 + b.y2) / 2];

export function intersection(a, b) {
  const w = Math.min(a.x2, b.x2) - Math.max(a.x1, b.x1);
  const h = Math.min(a.y2, b.y2) - Math.max(a.y1, b.y1);
  return Math.max(0, w) * Math.max(0, h);
}

export function iou(a, b) {
  const inter = intersection(a, b);
  const union = area(a) + area(b) - inter;
  return union > 0 ? inter / union : 0;
}

/** Per-class NMS: keep the most confident box among heavy overlaps. Stable, like sorted(). */
export function nonMaxSuppression(detections, threshold = 0.5) {
  const order = detections.map((d, i) => [d, i]).sort((a, b) => b[0].confidence - a[0].confidence || a[1] - b[1]);
  const kept = [];
  for (const [d] of order) {
    if (kept.every((k) => k.type !== d.type || iou(k.box, d.box) < threshold)) kept.push(d);
  }
  return kept;
}

function splitArches(teeth, imageHeight) {
  if (!teeth.length) return [[], []];
  const ordered = teeth.map((t, i) => [t, i]).sort((a, b) => center(a[0].box)[1] - center(b[0].box)[1] || a[1] - b[1]).map((p) => p[0]);
  if (ordered.length >= 2) {
    const ys = ordered.map((t) => center(t.box)[1]);
    let gap = -Infinity;
    let idx = -1;
    for (let i = 0; i < ys.length - 1; i++) {
      const g = ys[i + 1] - ys[i];
      if (g > gap || (g === gap && i > idx)) {
        gap = g;
        idx = i;
      }
    }
    const heights = ordered.map((t) => t.box.y2 - t.box.y1).sort((a, b) => a - b);
    const typical = heights[Math.floor(heights.length / 2)];
    if (gap >= typical * 0.5) return [ordered.slice(0, idx + 1), ordered.slice(idx + 1)];
  }
  const meanY = ordered.reduce((s, t) => s + center(t.box)[1], 0) / ordered.length;
  return meanY < imageHeight / 2 ? [ordered, []] : [[], ordered];
}

/**
 * FDI numbers on a panoramic image (patient's right on the viewer's left). Assumes a full
 * dentition without gaps; other modalities get "?".
 */
export function numberTeeth(toothDetections, imageWidth, imageHeight, modality) {
  if (modality !== "panoramic") return toothDetections.map((d) => ({ fdi: "?", confidence: d.confidence, box: d.box }));
  const midline = imageWidth / 2;
  const [upper, lower] = splitArches(toothDetections, imageHeight);
  const teeth = [];
  for (const [arch, [rightQ, leftQ]] of [[upper, [1, 2]], [lower, [4, 3]]]) {
    const stable = (list, key) => list.map((t, i) => [t, i]).sort((a, b) => key(a[0]) - key(b[0]) || a[1] - b[1]).map((p) => p[0]);
    const viewerLeft = stable(arch.filter((t) => center(t.box)[0] < midline), (t) => -center(t.box)[0]);
    const viewerRight = stable(arch.filter((t) => center(t.box)[0] >= midline), (t) => center(t.box)[0]);
    for (const [quadrant, side] of [[rightQ, viewerLeft], [leftQ, viewerRight]]) {
      side.forEach((d, i) => teeth.push({ fdi: i < 8 ? `${quadrant}${i + 1}` : "?", confidence: d.confidence, box: d.box }));
    }
  }
  return teeth;
}

export function assignTooth(box, teeth, minOverlap = 0.3) {
  const a = area(box);
  if (a <= 0) return null;
  let best = null;
  let bestShare = 0;
  for (const tooth of teeth) {
    const share = intersection(box, tooth.box) / a;
    if (share > bestShare) {
      best = tooth;
      bestShare = share;
    }
  }
  if (!best || bestShare < minOverlap || best.fdi === "?") return null;
  return best.fdi;
}

const toothOrder = (t) => [t.fdi === "?" ? 1 : 0, t.fdi];

export function buildFindings(detections, { width, height, modality, minConfidence = 0.25, reviewConfidence = 0.6 }) {
  const kept = nonMaxSuppression(detections.filter((d) => d.confidence >= minConfidence));
  const teeth = numberTeeth(kept.filter((d) => d.type === "tooth"), width, height, modality);
  const others = kept
    .filter((d) => d.type !== "tooth")
    .map((d, i) => [d, i])
    .sort((a, b) => b[0].confidence - a[0].confidence || a[1] - b[1])
    .map((p) => p[0]);
  const findings = others.map((d, i) => ({
    id: `F${i + 1}`,
    type: d.type,
    confidence: Math.round(d.confidence * 1000) / 1000,
    box: d.box,
    tooth: assignTooth(d.box, teeth),
    needsReview: d.confidence < reviewConfidence,
  }));
  teeth.sort((a, b) => {
    const [a0, a1] = toothOrder(a);
    const [b0, b1] = toothOrder(b);
    return a0 - b0 || (a1 < b1 ? -1 : a1 > b1 ? 1 : 0);
  });
  return { teeth, findings };
}

/** Best-effort radiograph type from DICOM description or shape (app.ingest.guess_modality). */
export function guessModality(width, height, hint = "") {
  const words = (hint || "").toLowerCase().match(/[a-z]+/g) || [];
  if (words.some((w) => w.startsWith("pan") || ["opg", "opt", "dpt"].includes(w))) return "panoramic";
  if (words.some((w) => w.startsWith("bitewing") || ["bw", "bwx"].includes(w))) return "bitewing";
  if (words.some((w) => w.startsWith("periapical") || ["pa", "iopa"].includes(w))) return "periapical";
  const aspect = height ? width / height : 0;
  if (aspect >= 1.7) return "panoramic";
  if (aspect >= 1.15) return "bitewing";
  if (aspect > 0) return "periapical";
  return "unknown";
}

/** All 32 permanent teeth in chart order (patient's right on the viewer's left). */
export const PERMANENT_TEETH = {
  upper: [18, 17, 16, 15, 14, 13, 12, 11, 21, 22, 23, 24, 25, 26, 27, 28].map(String),
  lower: [48, 47, 46, 45, 44, 43, 42, 41, 31, 32, 33, 34, 35, 36, 37, 38].map(String),
};
